/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Error { 
    /**
     * Наименование ошибки
     */
    name?: string;
    /**
     * Текст ошибки
     */
    message?: string;
    code?: number;
    status?: number;
}