/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GetmediaBody { 
    /**
     * Идентификатор Whatsapp ID
     */
    whatsappID?: string;
    /**
     * Идентификатор медиафайла, содержится во входящих сообщениях.
     */
    mediaKey?: string;
}