/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResponseChat } from './responseChat';

export interface InlineResponse2002 { 
    /**
     * при удачном исполнении запроса содержит OK
     */
    result?: string;
    /**
     * массив объектов ResponseChat
     */
    data?: Array<ResponseChat>;
}