/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Media { 
    /**
     * Mime type of file
     */
    mimetype: Media.MimetypeEnum;
    /**
     * Base64 encoded data file body
     */
    data: string;
    /**
     * Name of the file
     */
    filename: string;
}
export namespace Media {
    export type MimetypeEnum = 'application/ogg' | 'application/pdf' | 'application/zip' | 'application/gzip' | 'application/msword' | 'audio/mp4' | 'audio/aac' | 'audio/mpeg' | 'audio/ogg' | 'audio/webm' | 'image/gif' | 'image/jpeg' | 'image/pjpeg' | 'image/png' | 'image/svg+xml' | 'image/tiff' | 'image/webp' | 'video/mpeg' | 'video/mp4' | 'video/ogg' | 'video/quicktime' | 'video/webm' | 'video/x-ms-wmv' | 'video/x-flv' | 'application/vnd.ms-excel' | 'application/vnd.ms-powerpoint' | 'application/msword';
    export const MimetypeEnum = {
        Applicationogg: 'application/ogg' as MimetypeEnum,
        Applicationpdf: 'application/pdf' as MimetypeEnum,
        Applicationzip: 'application/zip' as MimetypeEnum,
        Applicationgzip: 'application/gzip' as MimetypeEnum,
        Applicationmsword: 'application/msword' as MimetypeEnum,
        Audiomp4: 'audio/mp4' as MimetypeEnum,
        Audioaac: 'audio/aac' as MimetypeEnum,
        Audiompeg: 'audio/mpeg' as MimetypeEnum,
        Audioogg: 'audio/ogg' as MimetypeEnum,
        Audiowebm: 'audio/webm' as MimetypeEnum,
        Imagegif: 'image/gif' as MimetypeEnum,
        Imagejpeg: 'image/jpeg' as MimetypeEnum,
        Imagepjpeg: 'image/pjpeg' as MimetypeEnum,
        Imagepng: 'image/png' as MimetypeEnum,
        Imagesvgxml: 'image/svg+xml' as MimetypeEnum,
        Imagetiff: 'image/tiff' as MimetypeEnum,
        Imagewebp: 'image/webp' as MimetypeEnum,
        Videompeg: 'video/mpeg' as MimetypeEnum,
        Videomp4: 'video/mp4' as MimetypeEnum,
        Videoogg: 'video/ogg' as MimetypeEnum,
        Videoquicktime: 'video/quicktime' as MimetypeEnum,
        Videowebm: 'video/webm' as MimetypeEnum,
        VideoxMsWmv: 'video/x-ms-wmv' as MimetypeEnum,
        VideoxFlv: 'video/x-flv' as MimetypeEnum,
        ApplicationvndMsExcel: 'application/vnd.ms-excel' as MimetypeEnum,
        ApplicationvndMsPowerpoint: 'application/vnd.ms-powerpoint' as MimetypeEnum,
        Applicationmsword_26: 'application/msword' as MimetypeEnum
    };
}