/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Media } from './media';

export interface MessageMedia { 
    body?: string;
    quote?: string;
    type?: MessageMedia.TypeEnum;
    media?: Media;
}
export namespace MessageMedia {
    export type TypeEnum = 'image' | 'sticker' | 'doc' | 'voice';
    export const TypeEnum = {
        Image: 'image' as TypeEnum,
        Sticker: 'sticker' as TypeEnum,
        Doc: 'doc' as TypeEnum,
        Voice: 'voice' as TypeEnum
    };
}