/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RecipientNum { 
    /**
     * Recipient number
     */
    number: string;
    /**
     * Recipient type, group or contact
     */
    type?: RecipientNum.TypeEnum;
}
export namespace RecipientNum {
    export type TypeEnum = 'group' | 'contact';
    export const TypeEnum = {
        Group: 'group' as TypeEnum,
        Contact: 'contact' as TypeEnum
    };
}