/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ResponseMessage { 
    /**
     * Идентификатор сообщения
     */
    id?: string;
    /**
     * Флаг просмотра сообщения
     */
    ack?: number;
    /**
     * Флаг, имеет ли сообщение медиафайл
     */
    hasMedia?: boolean;
    /**
     * Ключ медиафайла (при наличии)
     */
    mediaKey?: string;
    /**
     * Текст сообщения
     */
    body?: string;
    /**
     * Тип сообщения
     */
    type?: string;
    /**
     * Время сообщения в формате Unix Timestamp
     */
    timestamp?: number;
    /**
     * Идентификатор отправителя в формате WhatsApp
     */
    from?: string;
    /**
     * Идентификатор получателя в формате WhatsApp
     */
    to?: string;
    /**
     * Флаг, было ли сообщение перенаправлено
     */
    isForwarded?: boolean;
}