/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResponseChatGroupMetadata } from './responseChatGroupMetadata';

export interface ResponseChat { 
    /**
     * Идентификатор контакта или группы в формате WhatsApp
     */
    id?: string;
    /**
     * Имя контакта или группы
     */
    name?: string;
    /**
     * Является ли чат контактом или группой
     */
    isGroup?: boolean;
    /**
     * Является ли чат ReadOnly
     */
    isReadOnly?: boolean;
    /**
     * Количество непрочитанных сообщений в чате
     */
    unreadCount?: number;
    /**
     * Время последней активночти в чате
     */
    timestamp?: number;
    /**
     * Является ли чат закрепленным
     */
    pinned?: boolean;
    /**
     * Выключен ли у чата звук
     */
    isMuted?: boolean;
    /**
     * Время, оставшееся до включения звука
     */
    muteExpiration?: boolean;
    groupMetadata?: ResponseChatGroupMetadata;
}