/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResponseChatGroupMetadataParticipants } from './responseChatGroupMetadataParticipants';

/**
 * Метаданные группы, если чат является группой
 */
export interface ResponseChatGroupMetadata { 
    /**
     * Идентификатор группы в формате WhatsApp
     */
    id?: string;
    /**
     * Дата создания группы в формате Unix Time Stamp
     */
    creation?: number;
    /**
     * Идентификатор создателя группы в формате WhatsApp
     */
    owner?: string;
    /**
     * Количество участников в группе
     */
    size?: number;
    /**
     * Массив участников
     */
    participants?: Array<ResponseChatGroupMetadataParticipants>;
}