/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MessageMedia } from './messageMedia';
import { MessageText } from './messageText';
import { RecipientId } from './recipientId';
import { RecipientNum } from './recipientNum';

export interface SendBody { 
    /**
     * Service Whatsapp ID
     */
    whatsappID: string;
    /**
     * Async query returns Message Object
     */
    async?: boolean;
    recipient?: RecipientNum | RecipientId;
    message?: MessageText | MessageMedia;
}